baseurl: "http://mmakowski.github.io/blog/"
languageCode: "en-us"
title: "Maciek's blog"
theme: "xmin"
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    # - name: All
    #   url: ""
    #   weight: 1
    - name: Tech
      url: "technology/"
      weight: 2
    - name: Travel
      url: "travel/"
      weight: 3
    - name: Cook
      url: "cooking/"
      weight: 4

params:
  description: "MM TODO."
  footer: "&copy; [Maciek Makowski](https://mmakowski.com) 2010 -- {Year}"

markup:
  highlight:
    style: github
  goldmark:
    renderer:
      unsafe: true
