name = "MMin"
license = "MIT"
licenselink = "https://github.com/mmakowski/blog/themes/mmin/LICENSE.md"
description = "Maciek's blog theme"
# homepage = "https://xmin.yihui.org"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Maciek Makowski"
